const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  // Clear existing data
  await prisma.leasePlan.deleteMany({});
  await prisma.vehicle.deleteMany({});

  const vehicles = [
    // ────────────────────────────────────────────────
    // 2 WHEELER (7 vehicles)
    // ────────────────────────────────────────────────
    {
      make: "Ather",
      model: "450X Gen 3",
      category: "2 Wheeler",
      range: 159,
      topSpeed: 90,
      batteryCap: 3.7,
      basePrice: 2499,
      deposit: 7500,
      warranty: "3 years or 30,000 km",
      mainImage: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558981424-8612f1e74ee1?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 119,
      width: 750,
      height: 1140,
      length: 1850,
      groundClearance: 165,
      wheelbase: 1285,
      batteryType: "Lithium Ion",
      motorType: "PMS Motor",
      peakPower: "4.3 kW",
      peakTorque: "22 Nm",
      transmission: "Auto",
      gradability: 15,
      chargingTime: "6 Hrs 10 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Ather 450X Gen 3 is a premium electric scooter available for lease through ZMR Mobility, India's trusted EV partner. This electric scooter offers a certified range of 159 km, making it ideal for daily commuting and delivery operations.",
      techSpecsText: "The 450X Gen 3 charges fully in 6 Hours 10 Minutes. Powered by a 3.7 kWh battery (Lithium Ion technology), ensuring reliable performance and longevity.",
      performanceText: "Equipped with a PMS Motor delivering 4.3 kW peak power and 22 Nm torque, providing smooth and efficient performance. The scooter dimensions are 1850 mm (L) × 750 mm (W) × 1140 mm (H), designed for optimal maneuverability in urban traffic.",
      leasingInfoText: "The Ather 450X Gen 3 comes with 3 years or 30,000 km standard warranty, backed by ZMR Mobility's comprehensive support. Lease the Ather 450X starting from ₹2,499/month with flexible terms and all-inclusive packages."
    },
    {
      make: "Ola",
      model: "S1 Pro Gen 2",
      category: "2 Wheeler",
      range: 181,
      topSpeed: 120,
      batteryCap: 4.0,
      basePrice: 2999,
      deposit: 9000,
      warranty: "3 years or 50,000 km",
      mainImage: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1599912027611-484b9fc447af?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 125,
      width: 760,
      height: 1148,
      length: 1859,
      groundClearance: 165,
      wheelbase: 1310,
      batteryType: "NMC Lithium Ion",
      motorType: "Mid-drive Motor",
      peakPower: "8.5 kW",
      peakTorque: "58 Nm",
      transmission: "Auto",
      gradability: 18,
      chargingTime: "6 Hrs 30 Minutes",
      fastChargingTime: "0-50% in 25 Minutes (Hyper charger)",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Ola S1 Pro Gen 2 is a high-performance electric scooter available for lease through ZMR Mobility. With a certified range of 181 km and a blistering top speed of 120 km/h, it is perfect for riders who want premium performance without compromise.",
      techSpecsText: "The S1 Pro Gen 2 supports fast charging via Ola's Hyper Charger network, reaching 0-50% in 25 minutes. The 4.0 kWh NMC battery delivers exceptional energy density for long-range urban commutes.",
      performanceText: "Powered by a mid-drive motor producing 8.5 kW peak power and 58 Nm torque, the S1 Pro Gen 2 accelerates from 0-40 km/h in just 2.7 seconds. The vehicle dimensions are 1859 mm (L) × 760 mm (W) × 1148 mm (H).",
      leasingInfoText: "The Ola S1 Pro Gen 2 comes with 3 years or 50,000 km standard warranty, backed by ZMR Mobility's comprehensive support. Lease starting from ₹2,999/month with flexible tenure options."
    },
    {
      make: "TVS",
      model: "iQube S",
      category: "2 Wheeler",
      range: 145,
      topSpeed: 78,
      batteryCap: 3.4,
      basePrice: 1999,
      deposit: 6000,
      warranty: "3 years or 50,000 km",
      mainImage: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 118,
      width: 740,
      height: 1150,
      length: 1791,
      groundClearance: 145,
      wheelbase: 1270,
      batteryType: "Lithium Ion",
      motorType: "BLDC Hub Motor",
      peakPower: "4.4 kW",
      peakTorque: "140 Nm",
      transmission: "Auto",
      gradability: 12,
      chargingTime: "5 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The TVS iQube S is a feature-rich electric scooter available for lease through ZMR Mobility. With a certified range of 145 km and smart connectivity features, it is the ideal daily companion for urban professionals.",
      techSpecsText: "The iQube S charges fully in 5 Hours using its onboard 650W charger. Powered by a 3.4 kWh Lithium Ion battery with integrated BMS for safe and reliable performance.",
      performanceText: "The BLDC hub motor delivers 4.4 kW peak power and an impressive 140 Nm wheel torque, ensuring brisk acceleration from traffic signals. Vehicle dimensions: 1791 mm (L) × 740 mm (W) × 1150 mm (H).",
      leasingInfoText: "The TVS iQube S comes with 3 years or 50,000 km standard warranty. Lease starting from ₹1,999/month through ZMR Mobility with all-inclusive support packages."
    },
    {
      make: "Bajaj",
      model: "Chetak Premium",
      category: "2 Wheeler",
      range: 113,
      topSpeed: 73,
      batteryCap: 3.0,
      basePrice: 1799,
      deposit: 5500,
      warranty: "3 years or 50,000 km",
      mainImage: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 116,
      width: 726,
      height: 1103,
      length: 1795,
      groundClearance: 160,
      wheelbase: 1276,
      batteryType: "Lithium Ion Phosphate",
      motorType: "IPM Motor",
      peakPower: "3.8 kW",
      peakTorque: "16 Nm",
      transmission: "Auto",
      gradability: 10,
      chargingTime: "5 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Bajaj Chetak Premium blends iconic retro styling with modern EV technology. Available for lease through ZMR Mobility, this premium electric scooter is perfect for professionals who value both aesthetics and sustainability.",
      techSpecsText: "The Chetak Premium features an IP67-rated motor and battery pack for all-weather reliability. The 3.0 kWh LFP battery charges fully in 5 Hours using a standard 5A socket.",
      performanceText: "Powered by an IPM Motor producing 3.8 kW peak power and 16 Nm torque, offering smooth and refined performance. Dimensions: 1795 mm (L) × 726 mm (W) × 1103 mm (H) with a low step-through height for easy boarding.",
      leasingInfoText: "The Bajaj Chetak Premium comes with 3 years or 50,000 km warranty. Lease from ₹1,799/month through ZMR Mobility with zero-hassle maintenance packages."
    },
    {
      make: "Hero",
      model: "Vida V1 Pro",
      category: "2 Wheeler",
      range: 165,
      topSpeed: 80,
      batteryCap: 3.94,
      basePrice: 2299,
      deposit: 7000,
      warranty: "3 years or 50,000 km",
      mainImage: "https://images.unsplash.com/photo-1558981359-219d6364c9c8?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 136,
      width: 762,
      height: 1156,
      length: 1848,
      groundClearance: 168,
      wheelbase: 1295,
      batteryType: "NMC Lithium Ion",
      motorType: "PMSM Motor",
      peakPower: "6.0 kW",
      peakTorque: "25 Nm",
      transmission: "Auto",
      gradability: 14,
      chargingTime: "5 Hrs 15 Minutes",
      fastChargingTime: "0-80% in 1 Hr (Fast Charger)",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Hero Vida V1 Pro is India's latest flagship electric scooter from the world's largest two-wheeler manufacturer. Available through ZMR Mobility, it offers a 165 km certified range with fast charging capability for busy professionals.",
      techSpecsText: "The Vida V1 Pro supports optional fast charging, achieving 0-80% in just 1 Hour. The 3.94 kWh NMC battery pack is designed for 1,000+ charge cycles with minimal degradation.",
      performanceText: "Equipped with a 6.0 kW PMSM motor delivering 25 Nm torque, the Vida V1 Pro offers three riding modes — Eco, Ride, and Sports — for versatile urban and highway use. Dimensions: 1848 mm (L) × 762 mm (W) × 1156 mm (H).",
      leasingInfoText: "The Hero Vida V1 Pro comes with 3 years or 50,000 km warranty backed by Hero's pan-India service network. Lease from ₹2,299/month through ZMR Mobility."
    },
    {
      make: "Revolt",
      model: "RV400 BRZ",
      category: "2 Wheeler",
      range: 150,
      topSpeed: 85,
      batteryCap: 3.24,
      basePrice: 2199,
      deposit: 6500,
      warranty: "3 years or 40,000 km",
      mainImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 108,
      width: 800,
      height: 1090,
      length: 2025,
      groundClearance: 215,
      wheelbase: 1350,
      batteryType: "Lithium Ion",
      motorType: "BLDC Hub Motor",
      peakPower: "3.24 kW",
      peakTorque: "170 Nm",
      transmission: "Auto",
      gradability: 13,
      chargingTime: "4 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Revolt RV400 BRZ is India's only AI-enabled electric motorcycle available for lease through ZMR Mobility. With a motorcycle-style form factor and 150 km range, it appeals to riders seeking a sportier EV alternative to scooters.",
      techSpecsText: "The RV400 BRZ features swappable battery capability and 4-level regenerative braking. The 3.24 kWh Lithium Ion battery charges fully in 4.5 Hours, and the bike offers geo-fencing and over-the-air updates.",
      performanceText: "The BLDC hub motor produces 3.24 kW peak power and a massive 170 Nm wheel torque, giving the RV400 BRZ excellent hill-climbing ability. Dimensions: 2025 mm (L) × 800 mm (W) × 1090 mm (H) with 215 mm ground clearance.",
      leasingInfoText: "The Revolt RV400 BRZ comes with 3 years or 40,000 km warranty. Lease from ₹2,199/month through ZMR Mobility with flexible plans designed for delivery riders and daily commuters."
    },
    {
      make: "Simple",
      model: "One",
      category: "2 Wheeler",
      range: 212,
      topSpeed: 105,
      batteryCap: 4.8,
      basePrice: 2799,
      deposit: 8500,
      warranty: "3 years or 50,000 km",
      mainImage: "https://images.unsplash.com/photo-1558981285-6f0c68243e85?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 110,
      width: 735,
      height: 1105,
      length: 1830,
      groundClearance: 170,
      wheelbase: 1300,
      batteryType: "NMC Lithium Ion",
      motorType: "Mid-drive Motor",
      peakPower: "8.5 kW",
      peakTorque: "72 Nm",
      transmission: "Auto",
      gradability: 20,
      chargingTime: "4 Hrs 45 Minutes",
      fastChargingTime: "0-80% in 1 Hr 15 Min",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Simple One boasts the highest certified range of any electric scooter in India at 212 km. Available for lease through ZMR Mobility, it's engineered for riders who refuse to compromise between range, performance, and style.",
      techSpecsText: "The Simple One features a dual-battery architecture — a fixed cell and a portable cell — delivering 4.8 kWh total capacity. Fast charging brings it to 80% in 1 hour 15 minutes.",
      performanceText: "With 8.5 kW peak power and 72 Nm of torque, the Simple One achieves 0-40 km/h in 2.77 seconds. Four riding modes — Eco, Ride, Dash, and Sonic — cater to every use case. Dimensions: 1830 mm (L) × 735 mm (W) × 1105 mm (H).",
      leasingInfoText: "The Simple One comes with 3 years or 50,000 km warranty. Lease from ₹2,799/month through ZMR Mobility — the best range-per-rupee electric scooter on the market."
    },

    // ────────────────────────────────────────────────
    // 3 WHEELER (CARGO) — 7 vehicles
    // ────────────────────────────────────────────────
    {
      make: "Piaggio",
      model: "Ape E-Xtra",
      category: "3 Wheeler (Cargo)",
      range: 130,
      topSpeed: 45,
      batteryCap: 9.8,
      basePrice: 13499,
      deposit: 40000,
      warranty: "3 years or 90,000 km",
      mainImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 350,
      gvW: 750,
      width: 1420,
      height: 1720,
      length: 2990,
      groundClearance: 175,
      wheelbase: 2100,
      batteryType: "Lithium-ion Phosphate",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "4.7 kW",
      peakTorque: "35 Nm",
      transmission: "Auto",
      chargingTime: "6 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 400,
      volume: 22.5,
      containerDims: "1680 x 1420 x 1350",
      overviewText: "The Piaggio Ape E-Xtra is a reliable electric cargo loader available for lease through ZMR Mobility, India's trusted EV partner. This electric cargo loader offers a certified range of 130 km, making it ideal for daily delivery and logistics operations.",
      techSpecsText: "The Ape E-Xtra charges fully in 6 Hours. Powered by a 9.8 kWh battery (Lithium-ion Phosphate technology), ensuring reliable performance and longevity. With a payload capacity of 400 kg, the Ape E-Xtra is perfect for last-mile delivery operations.",
      performanceText: "The cargo area offers 22.5 ft³ of volume for bulky goods. The vehicle dimensions are 2990 mm (L) × 1420 mm (W) × 1720 mm (H), designed for optimal maneuverability in narrow city lanes.",
      leasingInfoText: "Equipped with a BLDC Motor delivering 4.7 kW peak power and 35 Nm torque. The Ape E-Xtra comes with 3 years or 90,000 km standard warranty. Lease from ₹13,499/month with flexible terms."
    },
    {
      make: "Bajaj",
      model: "Maxima XL E Tec 12.0",
      category: "3 Wheeler (Cargo)",
      range: 183,
      topSpeed: 45,
      batteryCap: 11.8,
      basePrice: 15999,
      deposit: 45000,
      warranty: "5 years or 120,000 km",
      mainImage: "https://images.unsplash.com/photo-1517657101434-8907957937b4?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 377,
      gvW: 805,
      width: 275,
      height: 1425,
      length: 1840,
      groundClearance: 180,
      wheelbase: 2274,
      batteryType: "Lithium-ion Phosphate",
      peakVoltage: 48,
      motorType: "PMS Motor",
      peakPower: "5.5 kW",
      peakTorque: "36 Nm",
      transmission: "Auto",
      chargingTime: "5 Hrs 50 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 500,
      volume: 25.46,
      containerDims: "1840 x 1425 x 275",
      overviewText: "The Bajaj Maxima XL E Tec 12.0 is an electric cargo loader available for lease through ZMR Mobility. With a certified range of 183 km and a 500 kg payload, it is ideal for daily operations and high-volume last-mile deliveries.",
      techSpecsText: "The Maxima XL E Tec 12.0 charges fully in 5 Hrs 50 Minutes. Powered by an 11.8 kWh LFP battery, ensuring reliable performance and longevity over 120,000 km.",
      performanceText: "The cargo area offers 25.46 ft³ of volume. Equipped with a PMS Motor delivering 5.5 kW peak power and 36 Nm torque. Vehicle dimensions: 1840 mm (L) × 275 mm (W) × 1425 mm (H).",
      leasingInfoText: "The Maxima XL E Tec 12.0 comes with 5 years or 120,000 km warranty, backed by ZMR Mobility's comprehensive support. Lease from ₹15,999/month with all-inclusive packages."
    },
    {
      make: "Mahindra",
      model: "Treo Zor",
      category: "3 Wheeler (Cargo)",
      range: 125,
      topSpeed: 45,
      batteryCap: 8.32,
      basePrice: 11999,
      deposit: 36000,
      warranty: "3 years or 80,000 km",
      mainImage: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1517657101434-8907957937b4?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 390,
      gvW: 890,
      width: 1425,
      height: 1870,
      length: 3135,
      groundClearance: 175,
      wheelbase: 2100,
      batteryType: "Lithium Ion",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "8.0 kW",
      peakTorque: "42 Nm",
      transmission: "Auto",
      chargingTime: "5 Hrs 45 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 500,
      volume: 28.0,
      containerDims: "1700 x 1425 x 1200",
      overviewText: "The Mahindra Treo Zor is a rugged electric cargo three-wheeler built for India's most demanding delivery conditions. Available through ZMR Mobility, it offers a 500 kg payload capacity and 125 km certified range.",
      techSpecsText: "The Treo Zor's 8.32 kWh Lithium Ion battery charges in 5 Hours 45 Minutes. Designed for commercial durability with IP65-rated battery protection suitable for monsoon conditions.",
      performanceText: "Powered by an 8.0 kW BLDC motor with 42 Nm torque, the Treo Zor handles steep inclines and heavy loads with ease. Cargo dimensions: 1700 mm (L) × 1425 mm (W) × 1200 mm (H) with 28 ft³ volume.",
      leasingInfoText: "The Mahindra Treo Zor comes with 3 years or 80,000 km warranty. Lease from ₹11,999/month through ZMR Mobility with Mahindra's pan-India service network backing every vehicle."
    },
    {
      make: "OSM",
      model: "Rage+ Frost",
      category: "3 Wheeler (Cargo)",
      range: 150,
      topSpeed: 45,
      batteryCap: 10.2,
      basePrice: 13999,
      deposit: 42000,
      warranty: "4 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 420,
      gvW: 960,
      width: 1480,
      height: 1900,
      length: 3200,
      groundClearance: 170,
      wheelbase: 2150,
      batteryType: "Lithium Ion Phosphate",
      peakVoltage: 60,
      motorType: "BLDC Motor",
      peakPower: "6.0 kW",
      peakTorque: "48 Nm",
      transmission: "Auto",
      chargingTime: "6 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 540,
      volume: 30.0,
      containerDims: "1800 x 1480 x 1250",
      overviewText: "The OSM Rage+ Frost is a next-generation electric cargo loader designed for India's cold chain and FMCG logistics. Available through ZMR Mobility, it offers a best-in-class 150 km range and 540 kg payload for commercial operations.",
      techSpecsText: "The Rage+ Frost features a 10.2 kWh LFP battery with active thermal management. The battery system is rated for extreme temperature performance, making it suitable for cold chain logistics operations.",
      performanceText: "A 6.0 kW BLDC motor produces 48 Nm torque — enough to handle fully loaded conditions on inclines. Cargo volume of 30 ft³ with reinforced floor plating. Dimensions: 3200 mm (L) × 1480 mm (W) × 1900 mm (H).",
      leasingInfoText: "The OSM Rage+ Frost comes with an industry-leading 4 years or 100,000 km warranty. Lease from ₹13,999/month through ZMR Mobility with dedicated fleet management support."
    },
    {
      make: "Altigreen",
      model: "neEV TE",
      category: "3 Wheeler (Cargo)",
      range: 151,
      topSpeed: 50,
      batteryCap: 10.0,
      basePrice: 14499,
      deposit: 43000,
      warranty: "5 years or 120,000 km",
      mainImage: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 405,
      gvW: 930,
      width: 1500,
      height: 1950,
      length: 3250,
      groundClearance: 180,
      wheelbase: 2180,
      batteryType: "Lithium Ion Phosphate",
      peakVoltage: 72,
      motorType: "PMS Motor",
      peakPower: "10.5 kW",
      peakTorque: "55 Nm",
      transmission: "Auto",
      chargingTime: "5 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 525,
      volume: 32.0,
      containerDims: "1900 x 1500 x 1300",
      overviewText: "The Altigreen neEV TE is a premium electric cargo three-wheeler engineered with Indian road conditions in mind. Available through ZMR Mobility, it offers India's highest payload capacity in its class with 525 kg and a 151 km certified range.",
      techSpecsText: "The neEV TE features a 10.0 kWh LFP battery with thermal management and smart BMS. With 72V architecture, it delivers more torque and better hill-climbing performance than competing 48V platforms.",
      performanceText: "A high-performance 10.5 kW PMS Motor produces 55 Nm torque, making it India's most powerful electric cargo three-wheeler. Cargo volume of 32 ft³. Dimensions: 3250 mm (L) × 1500 mm (W) × 1950 mm (H).",
      leasingInfoText: "The Altigreen neEV TE comes with 5 years or 120,000 km warranty. Lease from ₹14,499/month through ZMR Mobility — the highest-payload EV lease option in the three-wheeler segment."
    },
    {
      make: "Greaves",
      model: "Eltra Cargo",
      category: "3 Wheeler (Cargo)",
      range: 120,
      topSpeed: 45,
      batteryCap: 7.5,
      basePrice: 10999,
      deposit: 33000,
      warranty: "3 years or 80,000 km",
      mainImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 340,
      gvW: 790,
      width: 1400,
      height: 1800,
      length: 3000,
      groundClearance: 165,
      wheelbase: 2080,
      batteryType: "Lithium Ion",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "5.0 kW",
      peakTorque: "32 Nm",
      transmission: "Auto",
      chargingTime: "6 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 450,
      volume: 24.0,
      containerDims: "1650 x 1400 x 1200",
      overviewText: "The Greaves Eltra Cargo is a reliable and affordable electric cargo three-wheeler available through ZMR Mobility. With a 120 km range and 450 kg payload, it is ideal for small businesses and last-mile delivery operations.",
      techSpecsText: "The Eltra Cargo's 7.5 kWh Lithium Ion battery charges fully in 6 Hours. Backed by Greaves Electric's extensive after-sales network across 500+ cities in India.",
      performanceText: "A 5.0 kW BLDC motor provides 32 Nm torque for reliable daily operations. Cargo area offers 24 ft³ of volume. Vehicle dimensions: 3000 mm (L) × 1400 mm (W) × 1800 mm (H).",
      leasingInfoText: "The Greaves Eltra Cargo comes with 3 years or 80,000 km warranty. Lease from ₹10,999/month — the most affordable electric cargo lease option through ZMR Mobility."
    },
    {
      make: "Piaggio",
      model: "Ape E-City",
      category: "3 Wheeler (Cargo)",
      range: 143,
      topSpeed: 45,
      batteryCap: 11.2,
      basePrice: 14999,
      deposit: 44000,
      warranty: "3 years or 90,000 km",
      mainImage: "https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 380,
      gvW: 880,
      width: 1450,
      height: 1780,
      length: 3100,
      groundClearance: 175,
      wheelbase: 2130,
      batteryType: "Lithium-ion Phosphate",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "5.5 kW",
      peakTorque: "38 Nm",
      transmission: "Auto",
      chargingTime: "7 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      payload: 480,
      volume: 26.0,
      containerDims: "1720 x 1450 x 1300",
      overviewText: "The Piaggio Ape E-City is Piaggio's flagship electric cargo vehicle, designed for high-frequency city delivery. Available through ZMR Mobility, it offers an extended 143 km range with premium build quality synonymous with the Piaggio brand.",
      techSpecsText: "The Ape E-City features an 11.2 kWh LFP battery with advanced BMS for cycle longevity. The high-capacity battery enables full working-day operations without mid-day charging.",
      performanceText: "A 5.5 kW BLDC motor with 38 Nm torque handles urban stop-and-go traffic efficiently. Cargo capacity of 480 kg and 26 ft³ volume. Dimensions: 3100 mm (L) × 1450 mm (W) × 1780 mm (H).",
      leasingInfoText: "The Piaggio Ape E-City comes with 3 years or 90,000 km warranty. Lease from ₹14,999/month through ZMR Mobility with Piaggio's best-in-class after-sales support."
    },

    // ────────────────────────────────────────────────
    // 3 WHEELER (PASSENGER) — 7 vehicles
    // ────────────────────────────────────────────────
    {
      make: "Bajaj",
      model: "RE Tec 9.0",
      category: "3 Wheeler (Passenger)",
      range: 178,
      topSpeed: 45,
      batteryCap: 8.9,
      basePrice: 11199,
      deposit: 35000,
      warranty: "5 years or 120,000 km",
      mainImage: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 362,
      gvW: 708,
      width: 1300,
      height: 1700,
      length: 2635,
      groundClearance: 170,
      wheelbase: 2274,
      batteryType: "Lithium-ion Phosphate",
      peakVoltage: 48,
      motorType: "PMS Motor",
      peakPower: "4.5 kW",
      peakTorque: "36 Nm",
      transmission: "Auto",
      gradability: 29,
      chargingTime: "4 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Bajaj RE Tec 9.0 is an electric auto-rickshaw available for lease through ZMR Mobility. This electric auto-rickshaw offers a certified range of 178 km, making it ideal for daily operations and long-distance travel.",
      techSpecsText: "The RE Tec 9.0 charges fully in 4 Hours 30 Minutes. Powered by an 8.9 kWh battery (Lithium-ion Phosphate technology), ensuring reliable performance and longevity.",
      performanceText: "Equipped with a PMS Motor delivering 4.5 kW peak power and 36 Nm torque. Vehicle dimensions: 2635 mm (L) × 1300 mm (W) × 1700 mm (H), designed for optimal maneuverability in busy city streets.",
      leasingInfoText: "The RE Tec 9.0 comes with 5 years or 120,000 km standard warranty. Lease from ₹11,199/month through ZMR Mobility with flexible terms."
    },
    {
      make: "Mahindra",
      model: "Treo",
      category: "3 Wheeler (Passenger)",
      range: 130,
      topSpeed: 55,
      batteryCap: 7.37,
      basePrice: 9999,
      deposit: 30000,
      warranty: "3 years or 80,000 km",
      mainImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 370,
      gvW: 720,
      width: 1310,
      height: 1680,
      length: 2700,
      groundClearance: 170,
      wheelbase: 2075,
      batteryType: "Lithium Ion",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "8.0 kW",
      peakTorque: "42 Nm",
      transmission: "Auto",
      gradability: 28,
      chargingTime: "5 Hrs 40 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Mahindra Treo is India's best-selling electric auto-rickshaw, available for lease through ZMR Mobility. Trusted by over 100,000 drivers across India, it delivers a 130 km range with Mahindra's industry-leading after-sales support.",
      techSpecsText: "The Mahindra Treo features an IP65-rated battery pack and motor system, ensuring all-weather reliability including monsoon conditions. The 7.37 kWh Lithium Ion battery charges fully in 5 Hours 40 Minutes.",
      performanceText: "An 8.0 kW BLDC motor with 42 Nm torque ensures powerful performance on loaded conditions and uphill routes. Dimensions: 2700 mm (L) × 1310 mm (W) × 1680 mm (H).",
      leasingInfoText: "The Mahindra Treo comes with 3 years or 80,000 km warranty, backed by Mahindra's 500+ service centres. Lease from ₹9,999/month through ZMR Mobility."
    },
    {
      make: "OSM",
      model: "Stream City",
      category: "3 Wheeler (Passenger)",
      range: 165,
      topSpeed: 50,
      batteryCap: 9.5,
      basePrice: 10999,
      deposit: 33000,
      warranty: "4 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 385,
      gvW: 740,
      width: 1320,
      height: 1720,
      length: 2750,
      groundClearance: 175,
      wheelbase: 2100,
      batteryType: "Lithium Ion Phosphate",
      peakVoltage: 60,
      motorType: "BLDC Motor",
      peakPower: "7.5 kW",
      peakTorque: "44 Nm",
      transmission: "Auto",
      gradability: 27,
      chargingTime: "5 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The OSM Stream City is a modern electric passenger auto-rickshaw engineered for urban ride-hailing fleets. Available through ZMR Mobility, it offers a 165 km certified range — one of the highest in the passenger three-wheeler segment.",
      techSpecsText: "The Stream City features a 9.5 kWh LFP battery with active thermal management. It includes connected vehicle technology with GPS tracking and remote diagnostics for fleet operators.",
      performanceText: "A 7.5 kW BLDC motor with 44 Nm torque provides responsive city performance. The ergonomic cabin design accommodates 3 passengers comfortably. Dimensions: 2750 mm (L) × 1320 mm (W) × 1720 mm (H).",
      leasingInfoText: "The OSM Stream City comes with 4 years or 100,000 km warranty. Lease from ₹10,999/month through ZMR Mobility with fleet-optimized packages for ride-hailing operators."
    },
    {
      make: "Greaves",
      model: "Eltra Passenger",
      category: "3 Wheeler (Passenger)",
      range: 118,
      topSpeed: 50,
      batteryCap: 7.0,
      basePrice: 9499,
      deposit: 28500,
      warranty: "3 years or 75,000 km",
      mainImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 350,
      gvW: 700,
      width: 1290,
      height: 1660,
      length: 2650,
      groundClearance: 165,
      wheelbase: 2050,
      batteryType: "Lithium Ion",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "5.5 kW",
      peakTorque: "35 Nm",
      transmission: "Auto",
      gradability: 25,
      chargingTime: "5 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Greaves Eltra Passenger is an affordable electric auto-rickshaw available through ZMR Mobility. With Greaves' proven drivetrain technology and 118 km certified range, it is an excellent entry point for drivers transitioning to EV.",
      techSpecsText: "The Eltra Passenger's 7.0 kWh Lithium Ion battery charges fully in 5 Hours 30 Minutes. The vehicle supports swappable battery options in select cities for zero downtime operations.",
      performanceText: "A 5.5 kW BLDC motor with 35 Nm torque handles city traffic and mild gradients effectively. Vehicle dimensions: 2650 mm (L) × 1290 mm (W) × 1660 mm (H) for easy navigation in congested lanes.",
      leasingInfoText: "The Greaves Eltra Passenger comes with 3 years or 75,000 km warranty. Lease from ₹9,499/month — the most affordable passenger EV lease through ZMR Mobility."
    },
    {
      make: "YC",
      model: "Electric Auto",
      category: "3 Wheeler (Passenger)",
      range: 140,
      topSpeed: 50,
      batteryCap: 8.4,
      basePrice: 10499,
      deposit: 31500,
      warranty: "3 years or 80,000 km",
      mainImage: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 360,
      gvW: 715,
      width: 1305,
      height: 1700,
      length: 2710,
      groundClearance: 170,
      wheelbase: 2080,
      batteryType: "Lithium Ion Phosphate",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "6.0 kW",
      peakTorque: "38 Nm",
      transmission: "Auto",
      gradability: 26,
      chargingTime: "5 Hrs 15 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The YC Electric Auto is a purpose-built passenger three-wheeler for urban and semi-urban routes. Available through ZMR Mobility, it offers a 140 km certified range with a spacious cabin designed for passenger comfort.",
      techSpecsText: "The YC Electric Auto features an 8.4 kWh LFP battery with IP54-rated protection. The battery supports 2,000+ charge cycles for a durable commercial life exceeding 80,000 km.",
      performanceText: "A 6.0 kW BLDC motor with 38 Nm torque ensures consistent performance across varied terrain. Enhanced suspension tuning for passenger comfort on Indian roads. Dimensions: 2710 mm (L) × 1305 mm (W) × 1700 mm (H).",
      leasingInfoText: "The YC Electric Auto comes with 3 years or 80,000 km warranty. Lease from ₹10,499/month through ZMR Mobility with comprehensive roadside assistance coverage."
    },
    {
      make: "Piaggio",
      model: "Ape E-City Passenger",
      category: "3 Wheeler (Passenger)",
      range: 140,
      topSpeed: 45,
      batteryCap: 10.2,
      basePrice: 11999,
      deposit: 36000,
      warranty: "3 years or 90,000 km",
      mainImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 375,
      gvW: 730,
      width: 1315,
      height: 1710,
      length: 2680,
      groundClearance: 172,
      wheelbase: 2090,
      batteryType: "Lithium-ion Phosphate",
      peakVoltage: 48,
      motorType: "BLDC Motor",
      peakPower: "5.5 kW",
      peakTorque: "38 Nm",
      transmission: "Auto",
      gradability: 28,
      chargingTime: "6 Hrs 30 Minutes",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Piaggio Ape E-City Passenger is the electric variant of India's iconic Ape auto-rickshaw. Available through ZMR Mobility, it combines Piaggio's legendary Italian engineering with zero-emission performance for passenger transport.",
      techSpecsText: "The Ape E-City Passenger features a 10.2 kWh LFP battery providing a robust 140 km range on a single charge. The battery management system is optimised for Indian grid quality and temperature extremes.",
      performanceText: "Powered by a 5.5 kW BLDC motor with 38 Nm torque, providing smooth and efficient passenger transport. The ergonomic seating layout ensures comfort for 3 passengers. Dimensions: 2680 mm (L) × 1315 mm (W) × 1710 mm (H).",
      leasingInfoText: "The Piaggio Ape E-City Passenger comes with 3 years or 90,000 km warranty. Lease from ₹11,999/month through ZMR Mobility with Piaggio's trusted nationwide service network."
    },
    {
      make: "Euler",
      model: "HiLoad Passenger",
      category: "3 Wheeler (Passenger)",
      range: 148,
      topSpeed: 55,
      batteryCap: 9.0,
      basePrice: 11499,
      deposit: 34500,
      warranty: "5 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593696164805-967b967130e7?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 395,
      gvW: 760,
      width: 1340,
      height: 1730,
      length: 2760,
      groundClearance: 178,
      wheelbase: 2110,
      batteryType: "Lithium Ion Phosphate",
      peakVoltage: 60,
      motorType: "PMS Motor",
      peakPower: "8.5 kW",
      peakTorque: "46 Nm",
      transmission: "Auto",
      gradability: 30,
      chargingTime: "5 Hrs",
      chargerType: "Normal Charging",
      onBoardCharger: true,
      overviewText: "The Euler HiLoad Passenger is a high-performance electric passenger auto-rickshaw from Euler Motors. Available through ZMR Mobility, its 8.5 kW motor and 30% gradability make it the strongest performer on hilly terrain in the passenger segment.",
      techSpecsText: "The HiLoad Passenger's 9.0 kWh LFP battery charges fully in 5 Hours. The vehicle includes a connected telematics system for fleet monitoring, driver scoring, and remote diagnostics.",
      performanceText: "A powerful 8.5 kW PMS Motor with 46 Nm torque and 30% gradability rating makes the HiLoad Passenger ideal for hilly cities like Pune, Shimla, and Shillong. Dimensions: 2760 mm (L) × 1340 mm (W) × 1730 mm (H).",
      leasingInfoText: "The Euler HiLoad Passenger comes with 5 years or 100,000 km warranty. Lease from ₹11,499/month through ZMR Mobility — the best choice for tough terrain passenger operations."
    },

    // ────────────────────────────────────────────────
    // 4 WHEELER (PASSENGER) — 7 vehicles
    // ────────────────────────────────────────────────
    {
      make: "BYD",
      model: "eMax 7 Premium",
      category: "4 Wheeler (Passenger)",
      range: 530,
      topSpeed: 180,
      batteryCap: 55.4,
      basePrice: 58199,
      deposit: 174597,
      warranty: "6 years or 150,000 km",
      mainImage: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1800,
      gvW: 2374,
      width: 1810,
      height: 1690,
      length: 4710,
      groundClearance: 170,
      wheelbase: 2800,
      batteryType: "BYD Blade Battery",
      motorType: "AC Permanent magnet synchronous motor",
      peakPower: "120 kW",
      peakTorque: "310 Nm",
      transmission: "Auto",
      chargingTime: "37 Minutes",
      fastChargingTime: "0-80% in 37 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The BYD eMax 7 Premium is a premium electric MPV available for lease through ZMR Mobility. With a 530 km certified range and 7-seater capacity, it is the ideal vehicle for corporate fleets and ride-hailing operators.",
      techSpecsText: "The eMax 7 Premium charges 0-80% in just 37 Minutes with DC fast charging. Powered by BYD's proprietary Blade Battery (55.4 kWh), which offers superior thermal safety compared to conventional lithium-ion.",
      performanceText: "Equipped with a 120 kW permanent magnet synchronous motor producing 310 Nm torque. The 7-seater MPV body offers class-leading interior space. Dimensions: 4710 mm (L) × 1810 mm (W) × 1690 mm (H).",
      leasingInfoText: "The BYD eMax 7 Premium comes with 6 years or 150,000 km warranty. Lease from ₹58,199/month through ZMR Mobility with corporate fleet packages available."
    },
    {
      make: "Tata",
      model: "Nexon EV MAX",
      category: "4 Wheeler (Passenger)",
      range: 437,
      topSpeed: 150,
      batteryCap: 40.5,
      basePrice: 32999,
      deposit: 99000,
      warranty: "8 years or 160,000 km",
      mainImage: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1545,
      gvW: 2000,
      width: 1811,
      height: 1606,
      length: 3993,
      groundClearance: 209,
      wheelbase: 2498,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet Synchronous Motor",
      peakPower: "143 kW",
      peakTorque: "215 Nm",
      transmission: "Auto",
      chargingTime: "8 Hrs 45 Minutes",
      fastChargingTime: "0-80% in 56 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Tata Nexon EV MAX is India's highest-selling electric SUV, available for lease through ZMR Mobility. With a 437 km ARAI-certified range, best-in-class 209 mm ground clearance, and 5-star safety rating, it is ideal for families and corporate fleets.",
      techSpecsText: "The Nexon EV MAX features a 40.5 kWh NMC battery pack supporting fast charging (0-80% in 56 minutes via 50 kW DC charger). The battery warranty is an industry-leading 8 years or 160,000 km.",
      performanceText: "A 143 kW PMSM motor produces 215 Nm torque for spirited performance. The high 209 mm ground clearance makes it suitable for both city roads and weekend getaways. Dimensions: 3993 mm (L) × 1811 mm (W) × 1606 mm (H).",
      leasingInfoText: "The Tata Nexon EV MAX comes with 8 years or 160,000 km battery warranty. Lease from ₹32,999/month through ZMR Mobility — India's most trusted EV lease."
    },
    {
      make: "MG",
      model: "ZS EV Excite+",
      category: "4 Wheeler (Passenger)",
      range: 461,
      topSpeed: 175,
      batteryCap: 50.3,
      basePrice: 39999,
      deposit: 120000,
      warranty: "5 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1620,
      gvW: 2095,
      width: 1809,
      height: 1649,
      length: 4314,
      groundClearance: 177,
      wheelbase: 2585,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet Synchronous Motor",
      peakPower: "130 kW",
      peakTorque: "280 Nm",
      transmission: "Auto",
      chargingTime: "8 Hrs 30 Minutes",
      fastChargingTime: "0-80% in 60 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The MG ZS EV Excite+ is a feature-loaded electric SUV available for lease through ZMR Mobility. With a 461 km certified range and premium connected car features, it appeals to tech-savvy urban professionals.",
      techSpecsText: "The ZS EV Excite+ houses a 50.3 kWh NMC battery supporting both AC and DC fast charging. The vehicle features Vehicle-to-Load (V2L) capability, turning it into a portable power station.",
      performanceText: "A 130 kW PMSM motor produces 280 Nm torque for confident overtaking. The spacious 5-seater cabin features a panoramic sunroof and 10.1-inch infotainment. Dimensions: 4314 mm (L) × 1809 mm (W) × 1649 mm (H).",
      leasingInfoText: "The MG ZS EV Excite+ comes with 5 years or 100,000 km vehicle warranty and 8 years battery warranty. Lease from ₹39,999/month through ZMR Mobility."
    },
    {
      make: "Tata",
      model: "Tigor EV XZ+",
      category: "4 Wheeler (Passenger)",
      range: 306,
      topSpeed: 120,
      batteryCap: 26.0,
      basePrice: 21999,
      deposit: 66000,
      warranty: "8 years or 160,000 km",
      mainImage: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1225,
      gvW: 1650,
      width: 1677,
      height: 1537,
      length: 3993,
      groundClearance: 165,
      wheelbase: 2450,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet AC Motor",
      peakPower: "55 kW",
      peakTorque: "170 Nm",
      transmission: "Auto",
      chargingTime: "8 Hrs 45 Minutes",
      fastChargingTime: "0-80% in 65 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Tata Tigor EV XZ+ is the most affordable electric sedan available for lease through ZMR Mobility. Perfect for urban commuting, ride-hailing fleets, and corporate pool cars, it delivers 306 km of certified range in a compact, practical package.",
      techSpecsText: "The Tigor EV XZ+ features a 26 kWh NMC battery with Tata's Ziptron EV technology — same platform trusted by Tata's commercial fleet programs. 8-year battery warranty offers peace of mind.",
      performanceText: "A 55 kW PMAC motor with 170 Nm torque delivers smooth urban acceleration. The compact dimensions (3993 mm L × 1677 mm W × 1537 mm H) make it highly manoeuvrable in city traffic.",
      leasingInfoText: "The Tata Tigor EV XZ+ comes with 8 years or 160,000 km battery warranty. Lease from ₹21,999/month — the most affordable 4-wheeler EV lease through ZMR Mobility."
    },
    {
      make: "Tata",
      model: "Punch EV Empowered+",
      category: "4 Wheeler (Passenger)",
      range: 421,
      topSpeed: 140,
      batteryCap: 35.0,
      basePrice: 27999,
      deposit: 84000,
      warranty: "8 years or 160,000 km",
      mainImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1385,
      gvW: 1850,
      width: 1742,
      height: 1633,
      length: 3827,
      groundClearance: 187,
      wheelbase: 2445,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet Synchronous Motor",
      peakPower: "99 kW",
      peakTorque: "190 Nm",
      transmission: "Auto",
      chargingTime: "7 Hrs 30 Minutes",
      fastChargingTime: "0-80% in 56 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Tata Punch EV Empowered+ is a micro-SUV with premium EV capabilities, available for lease through ZMR Mobility. With 421 km range and 5-star NCAP safety rating, it is one of the safest and most practical EVs for Indian families.",
      techSpecsText: "The Punch EV Empowered+ features a 35 kWh NMC battery with V2L (Vehicle-to-Load) capability. It supports both AC charging (7.2 kW) and DC fast charging (50 kW), with the Tata Motors app for remote monitoring.",
      performanceText: "A 99 kW PMSM motor with 190 Nm torque and four driving modes — Eco, City, Sport, and Sport+ — for every driving scenario. High 187 mm ground clearance for confident driving. Dimensions: 3827 mm (L) × 1742 mm (W) × 1633 mm (H).",
      leasingInfoText: "The Tata Punch EV Empowered+ comes with 8 years or 160,000 km battery warranty. Lease from ₹27,999/month through ZMR Mobility with all-inclusive service packages."
    },
    {
      make: "Hyundai",
      model: "Creta Electric Executive",
      category: "4 Wheeler (Passenger)",
      range: 473,
      topSpeed: 155,
      batteryCap: 51.4,
      basePrice: 44999,
      deposit: 135000,
      warranty: "3 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1730,
      gvW: 2205,
      width: 1825,
      height: 1635,
      length: 4315,
      groundClearance: 200,
      wheelbase: 2610,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet Synchronous Motor",
      peakPower: "135 kW",
      peakTorque: "310 Nm",
      transmission: "Auto",
      chargingTime: "4 Hrs",
      fastChargingTime: "0-80% in 58 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Hyundai Creta Electric Executive is India's most anticipated electric SUV, available for lease through ZMR Mobility. Built on Hyundai's proven global EV platform, it delivers 473 km range with the most feature-rich cabin in its segment.",
      techSpecsText: "The Creta Electric features a 51.4 kWh NMC battery supporting 11 kW AC fast charging and 50 kW DC charging. V2L capability allows the vehicle to power external devices up to 3.3 kW.",
      performanceText: "A 135 kW PMSM motor delivers 310 Nm torque with a 0-100 km/h time of 7.9 seconds. The panoramic curved display, advanced ADAS suite, and 200 mm ground clearance set new benchmarks. Dimensions: 4315 mm (L) × 1825 mm (W) × 1635 mm (H).",
      leasingInfoText: "The Hyundai Creta Electric Executive comes with 3 years or 100,000 km vehicle warranty and 8 years battery warranty. Lease from ₹44,999/month through ZMR Mobility."
    },
    {
      make: "Kia",
      model: "EV6 GT-Line",
      category: "4 Wheeler (Passenger)",
      range: 528,
      topSpeed: 185,
      batteryCap: 77.4,
      basePrice: 79999,
      deposit: 240000,
      warranty: "7 years or 150,000 km",
      mainImage: "https://images.unsplash.com/photo-1623869675781-80aa31012b01?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1960,
      gvW: 2460,
      width: 1880,
      height: 1550,
      length: 4695,
      groundClearance: 160,
      wheelbase: 2900,
      batteryType: "NMC Lithium Ion",
      motorType: "Dual Permanent Magnet Synchronous Motor (AWD)",
      peakPower: "239 kW",
      peakTorque: "605 Nm",
      transmission: "Auto",
      chargingTime: "18 Minutes",
      fastChargingTime: "0-80% in 18 Minutes (800V ultra-fast)",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      overviewText: "The Kia EV6 GT-Line is a global award-winning electric crossover available for lease through ZMR Mobility. Its 800V ultra-fast charging architecture charges from 10% to 80% in just 18 minutes — the fastest in India.",
      techSpecsText: "The EV6 GT-Line's 77.4 kWh NMC battery supports 800V ultra-fast charging, accepting up to 350 kW DC input. The bi-directional charging enables V2L (3.6 kW) and V2H (vehicle-to-home) capability.",
      performanceText: "Dual PMSM motors produce 239 kW peak power and 605 Nm torque, enabling 0-100 km/h in 5.1 seconds. The sleek crossover design and 528 km range make it ideal for executive travel. Dimensions: 4695 mm (L) × 1880 mm (W) × 1550 mm (H).",
      leasingInfoText: "The Kia EV6 GT-Line comes with 7 years or 150,000 km warranty. Lease from ₹79,999/month through ZMR Mobility — the ultimate premium EV lease for executives."
    },

    // ────────────────────────────────────────────────
    // 4 WHEELER (CARGO) — 7 vehicles
    // ────────────────────────────────────────────────
    {
      make: "Euler",
      model: "Storm EVT 1250",
      category: "4 Wheeler (Cargo)",
      range: 210,
      trueRange: 140,
      topSpeed: 70,
      batteryCap: 6.6,
      basePrice: 23799,
      deposit: 70000,
      warranty: "5 years or 150,000 km",
      mainImage: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1350,
      gvW: 2600,
      width: 1560,
      height: 2685,
      length: 4125,
      groundClearance: 175,
      wheelbase: 2170,
      batteryType: "Lithium Ion",
      motorType: "PMS Motor",
      peakPower: "30 kW",
      peakTorque: "140 Nm",
      transmission: "Manual",
      gradability: 22,
      chargingTime: "6 Hrs",
      fastChargingTime: "30 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1250,
      volume: 260.0,
      containerDims: "2547 x 1538 x 1900",
      overviewText: "The Euler Storm EVT 1250 is an electric cargo vehicle available for lease through ZMR Mobility. With a 1250 kg payload and 210 km certified range, it is India's most capable electric cargo van.",
      techSpecsText: "The Storm EVT 1250 supports fast charging (30 Minutes to 80%). Powered by a 6.6 kWh Lithium Ion battery with a high-performance 30 kW motor.",
      performanceText: "The cargo area offers 260 ft³ for bulky goods with a 2547 mm (L) × 1538 mm (W) × 1900 mm (H) container. The 30 kW PMS Motor with 140 Nm torque ensures confident highway running.",
      leasingInfoText: "The Euler Storm EVT 1250 comes with 5 years or 150,000 km warranty. Lease from ₹23,799/month through ZMR Mobility with fleet management tools included."
    },
    {
      make: "Tata",
      model: "Ace EV",
      category: "4 Wheeler (Cargo)",
      range: 154,
      trueRange: 100,
      topSpeed: 70,
      batteryCap: 21.3,
      basePrice: 19999,
      deposit: 60000,
      warranty: "5 years or 120,000 km",
      mainImage: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1365,
      gvW: 2515,
      width: 1550,
      height: 2600,
      length: 4040,
      groundClearance: 175,
      wheelbase: 2100,
      batteryType: "NMC Lithium Ion",
      motorType: "Permanent Magnet AC Motor",
      peakPower: "35 kW",
      peakTorque: "130 Nm",
      transmission: "Auto",
      gradability: 24,
      chargingTime: "5 Hrs 30 Minutes",
      fastChargingTime: "0-80% in 70 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1150,
      volume: 220.0,
      containerDims: "2400 x 1540 x 1800",
      overviewText: "The Tata Ace EV is the electric version of India's most popular small commercial vehicle, available for lease through ZMR Mobility. Trusted by over 1 million businesses, the Ace EV brings zero-emission reliability to last-mile logistics.",
      techSpecsText: "The Tata Ace EV features a 21.3 kWh NMC battery supporting AC charging (7.2 kW) and DC fast charging (0-80% in 70 minutes). The auto transmission reduces driver fatigue in city stop-and-go conditions.",
      performanceText: "A 35 kW PMAC motor with 130 Nm torque and 24% gradability handles fully loaded operations on city gradients. Cargo capacity of 1150 kg with 220 ft³ volume. Dimensions: 4040 mm (L) × 1550 mm (W) × 2600 mm (H).",
      leasingInfoText: "The Tata Ace EV comes with 5 years or 120,000 km warranty and Tata Motors' pan-India service network. Lease from ₹19,999/month through ZMR Mobility."
    },
    {
      make: "Mahindra",
      model: "Treo Zor Cargo 4W",
      category: "4 Wheeler (Cargo)",
      range: 175,
      trueRange: 120,
      topSpeed: 65,
      batteryCap: 15.6,
      basePrice: 17999,
      deposit: 54000,
      warranty: "3 years or 80,000 km",
      mainImage: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1280,
      gvW: 2430,
      width: 1520,
      height: 2550,
      length: 3850,
      groundClearance: 170,
      wheelbase: 2000,
      batteryType: "Lithium Ion",
      motorType: "BLDC Motor",
      peakPower: "25 kW",
      peakTorque: "115 Nm",
      transmission: "Auto",
      gradability: 20,
      chargingTime: "6 Hrs",
      fastChargingTime: "0-80% in 75 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1150,
      volume: 200.0,
      containerDims: "2200 x 1500 x 1700",
      overviewText: "The Mahindra Treo Zor Cargo 4W is a four-wheeled electric cargo vehicle built on Mahindra's proven EV platform. Available through ZMR Mobility, it combines the maneuverability of a three-wheeler with the stability and payload of a full cargo van.",
      techSpecsText: "The Treo Zor Cargo 4W features a 15.6 kWh Lithium Ion battery with IP65 protection rated for all-weather operation. Fast charging support brings it to 80% in 75 minutes.",
      performanceText: "A 25 kW BLDC motor with 115 Nm torque handles urban delivery routes and industrial areas efficiently. Cargo volume of 200 ft³ with reinforced load floor. Dimensions: 3850 mm (L) × 1520 mm (W) × 2550 mm (H).",
      leasingInfoText: "The Mahindra Treo Zor Cargo 4W comes with 3 years or 80,000 km warranty. Lease from ₹17,999/month through ZMR Mobility with Mahindra's extensive service coverage."
    },
    {
      make: "Piaggio",
      model: "Porter Electric",
      category: "4 Wheeler (Cargo)",
      range: 160,
      trueRange: 110,
      topSpeed: 60,
      batteryCap: 17.5,
      basePrice: 18499,
      deposit: 55500,
      warranty: "3 years or 90,000 km",
      mainImage: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1310,
      gvW: 2460,
      width: 1530,
      height: 2580,
      length: 3960,
      groundClearance: 172,
      wheelbase: 2050,
      batteryType: "Lithium Ion Phosphate",
      motorType: "BLDC Motor",
      peakPower: "22 kW",
      peakTorque: "120 Nm",
      transmission: "Auto",
      gradability: 18,
      chargingTime: "7 Hrs",
      fastChargingTime: "0-80% in 80 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1150,
      volume: 215.0,
      containerDims: "2300 x 1510 x 1800",
      overviewText: "The Piaggio Porter Electric is the electric evolution of Piaggio's iconic Porter cargo vehicle. Available through ZMR Mobility, it brings Piaggio's legendary build quality to zero-emission logistics with a 160 km certified range.",
      techSpecsText: "The Porter Electric features a 17.5 kWh LFP battery with IP54-rated protection. The battery management system is optimised for high-cycle commercial use, targeting 2,000+ charge cycles.",
      performanceText: "A 22 kW BLDC motor with 120 Nm torque delivers reliable city and suburban logistics performance. Cargo volume of 215 ft³ with side access doors. Dimensions: 3960 mm (L) × 1530 mm (W) × 2580 mm (H).",
      leasingInfoText: "The Piaggio Porter Electric comes with 3 years or 90,000 km warranty. Lease from ₹18,499/month through ZMR Mobility with Piaggio's nationwide service support."
    },
    {
      make: "Altigreen",
      model: "neEV HE",
      category: "4 Wheeler (Cargo)",
      range: 200,
      trueRange: 130,
      topSpeed: 75,
      batteryCap: 20.0,
      basePrice: 21499,
      deposit: 64500,
      warranty: "5 years or 150,000 km",
      mainImage: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1420,
      gvW: 2720,
      width: 1580,
      height: 2720,
      length: 4200,
      groundClearance: 180,
      wheelbase: 2200,
      batteryType: "Lithium Ion Phosphate",
      motorType: "PMS Motor",
      peakPower: "40 kW",
      peakTorque: "160 Nm",
      transmission: "Auto",
      gradability: 25,
      chargingTime: "5 Hrs",
      fastChargingTime: "0-80% in 55 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1300,
      volume: 275.0,
      containerDims: "2600 x 1560 x 1950",
      overviewText: "The Altigreen neEV HE is India's most advanced electric cargo van, available for lease through ZMR Mobility. With the highest payload in its class (1300 kg) and a powerful 40 kW motor, it is engineered for demanding e-commerce and FMCG distribution.",
      techSpecsText: "The neEV HE features a 20.0 kWh LFP battery with active thermal management and fast charging support (0-80% in 55 minutes). The advanced BMS enables real-time fleet monitoring via the Altigreen connected platform.",
      performanceText: "A 40 kW PMS Motor with 160 Nm torque and 25% gradability makes the neEV HE the most powerful electric cargo van in India. Cargo volume of 275 ft³ — the largest in its class. Dimensions: 4200 mm (L) × 1580 mm (W) × 2720 mm (H).",
      leasingInfoText: "The Altigreen neEV HE comes with 5 years or 150,000 km warranty. Lease from ₹21,499/month through ZMR Mobility — the best payload-per-rupee lease in the 4-wheeler cargo segment."
    },
    {
      make: "Euler",
      model: "HiLoad EV",
      category: "4 Wheeler (Cargo)",
      range: 195,
      trueRange: 135,
      topSpeed: 70,
      batteryCap: 19.0,
      basePrice: 20999,
      deposit: 63000,
      warranty: "5 years or 150,000 km",
      mainImage: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1380,
      gvW: 2680,
      width: 1570,
      height: 2700,
      length: 4150,
      groundClearance: 178,
      wheelbase: 2190,
      batteryType: "Lithium Ion",
      motorType: "PMS Motor",
      peakPower: "36 kW",
      peakTorque: "150 Nm",
      transmission: "Auto",
      gradability: 23,
      chargingTime: "6 Hrs",
      fastChargingTime: "0-80% in 60 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1280,
      volume: 265.0,
      containerDims: "2560 x 1550 x 1920",
      overviewText: "The Euler HiLoad EV is a purpose-built electric cargo van designed for India's demanding logistics sector. Available through ZMR Mobility, it offers a 1280 kg payload, 195 km range, and class-leading connected fleet management features.",
      techSpecsText: "The HiLoad EV features a 19.0 kWh Lithium Ion battery with OTA (over-the-air) update capability. The Euler connected platform provides real-time vehicle health, driver behaviour scoring, and route optimisation for fleet operators.",
      performanceText: "A 36 kW PMS Motor with 150 Nm torque and auto transmission ensures efficient operations. Cargo volume of 265 ft³ with rear and side loading options. Dimensions: 4150 mm (L) × 1570 mm (W) × 2700 mm (H).",
      leasingInfoText: "The Euler HiLoad EV comes with 5 years or 150,000 km warranty with dedicated fleet management support. Lease from ₹20,999/month through ZMR Mobility."
    },
    {
      make: "OSM",
      model: "Rage+ Cargo 4W",
      category: "4 Wheeler (Cargo)",
      range: 180,
      trueRange: 120,
      topSpeed: 65,
      batteryCap: 16.5,
      basePrice: 18999,
      deposit: 57000,
      warranty: "4 years or 100,000 km",
      mainImage: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=1200",
      sideImages: "https://images.unsplash.com/photo-1593123253302-36b761794713?auto=format&fit=crop&q=80&w=1200,https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=1200",
      kerbWeight: 1300,
      gvW: 2500,
      width: 1545,
      height: 2650,
      length: 4000,
      groundClearance: 173,
      wheelbase: 2100,
      batteryType: "Lithium Ion Phosphate",
      motorType: "BLDC Motor",
      peakPower: "28 kW",
      peakTorque: "125 Nm",
      transmission: "Auto",
      gradability: 20,
      chargingTime: "6 Hrs 30 Minutes",
      fastChargingTime: "0-80% in 70 Minutes",
      chargerType: "Fast Charging",
      onBoardCharger: true,
      payload: 1200,
      volume: 235.0,
      containerDims: "2450 x 1525 x 1850",
      overviewText: "The OSM Rage+ Cargo 4W is a versatile electric cargo van from Omega Seiki Mobility, available through ZMR Mobility. Designed for India's urban and semi-urban logistics needs, it offers reliable 180 km range and 1200 kg payload capacity.",
      techSpecsText: "The Rage+ Cargo 4W features a 16.5 kWh LFP battery with OSM's connected vehicle platform for GPS tracking, geofencing, and remote diagnostics. Fleet management integration is available out-of-the-box.",
      performanceText: "A 28 kW BLDC motor with 125 Nm torque delivers dependable daily performance for e-commerce and FMCG deliveries. Cargo volume of 235 ft³. Dimensions: 4000 mm (L) × 1545 mm (W) × 2650 mm (H).",
      leasingInfoText: "The OSM Rage+ Cargo 4W comes with 4 years or 100,000 km warranty. Lease from ₹18,999/month through ZMR Mobility with comprehensive fleet support packages."
    }
  ];

  for (const vehicle of vehicles) {
    await prisma.vehicle.create({
      data: vehicle
    });
  }

  console.log(`Seeded ${vehicles.length} vehicles across all categories!`);
  const counts = vehicles.reduce((acc, v) => {
    acc[v.category] = (acc[v.category] || 0) + 1;
    return acc;
  }, {});
  console.table(counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
