import React from "react";

export const metadata = {
  title: "Terms and Conditions | ZMR Mobility",
  description: "Read the terms and conditions for using ZMR Mobility's platform and services.",
};

export default function TermsAndConditions() {
  return (
    <main className="min-h-screen bg-background text-ink pt-24 lg:pt-40 pb-20 px-6">
      <div className="max-w-4xl mx-auto">
        <div className="mb-12">
          <span className="text-primary text-xs font-bold uppercase tracking-widest">Legal</span>
          <h1 className="text-4xl md:text-5xl font-black mt-3 mb-4">Terms & <span className="text-primary">Conditions</span></h1>
          <p className="text-ink/60">Last Updated: May 10, 2026</p>
        </div>

        <div className="space-y-10 prose prose-slate prose-primary max-w-none">
          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">1. Agreement to Terms</h2>
            <p className="text-ink/70 leading-relaxed">
              By accessing or using the ZMR Mobility website and services (the "Services"), you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not access the Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">2. Eligibility</h2>
            <p className="text-ink/70 leading-relaxed">
              To use our Services, you must be at least 18 years of age and possess the legal authority to enter into a binding agreement. By using the Services, you represent and warrant that you meet these requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">3. Leasing Services</h2>
            <p className="text-ink/70 leading-relaxed">
              ZMR Mobility provides electric vehicle leasing solutions. All lease agreements are subject to:
            </p>
            <ul className="list-disc list-inside text-ink/70 mt-4 space-y-2">
              <li>Successful KYC verification and credit assessment.</li>
              <li>Execution of a formal Lease Agreement.</li>
              <li>Payment of the security deposit and advanced rentals as specified.</li>
              <li>Adherence to vehicle usage and maintenance guidelines.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">4. IoT and Vehicle Monitoring</h2>
            <p className="text-ink/70 leading-relaxed">
              All vehicles leased through ZMR Mobility are equipped with IoT devices for real-time monitoring of location, performance, and health. You agree to:
            </p>
            <ul className="list-disc list-inside text-ink/70 mt-4 space-y-2">
              <li>Not tamper with, disable, or remove any IoT or telematics equipment.</li>
              <li>Allow the Company to track the vehicle's location and usage data.</li>
              <li>Follow maintenance alerts generated by the system.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">5. User Responsibilities</h2>
            <p className="text-ink/70 leading-relaxed">
              As a user of our platform and vehicles, you are responsible for:
            </p>
            <ul className="list-disc list-inside text-ink/70 mt-4 space-y-2">
              <li>Providing accurate and complete information during application.</li>
              <li>Maintaining the confidentiality of your account credentials.</li>
              <li>Using the vehicle only for the purposes agreed upon in the lease.</li>
              <li>Complying with all local traffic laws and regulations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">6. Intellectual Property</h2>
            <p className="text-ink/70 leading-relaxed">
              All content, logos, software, and designs on this platform are the exclusive property of ZMR Mobility Private Limited. You may not reproduce, distribute, or create derivative works without our express written consent.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">7. Limitation of Liability</h2>
            <p className="text-ink/70 leading-relaxed">
              To the maximum extent permitted by law, ZMR Mobility shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Services or the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">8. Governing Law</h2>
            <p className="text-ink/70 leading-relaxed">
              These Terms and Conditions shall be governed by and construed in accordance with the laws of India. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in Lucknow, Uttar Pradesh.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">9. Changes to Terms</h2>
            <p className="text-ink/70 leading-relaxed">
              We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new terms on this page. Your continued use of the Services after such changes constitutes your acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-ink mb-4">10. Contact Information</h2>
            <p className="text-ink/70 leading-relaxed">
              If you have any questions about these Terms and Conditions, please contact us at:
            </p>
            <div className="mt-4 p-6 glass-card border-ink/[0.08] bg-ink/[0.02]">
              <p className="font-bold text-ink">Legal Department</p>
              <p className="text-ink/70 text-sm mt-1">ZMR Mobility Private Limited</p>
              <p className="text-ink/70 text-sm">Email: contact@zmrmobility.com</p>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}
